### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by kelteseth** [mpreisler/mingw-bundledlls#12]
Hi,

I'm not really a python guy so I'm not sure whats the problem here:
```
PS C:\Users\Eli\Code\Qt\build-krita-Desktop_Qt_MinGW_w64_64bit_MSYS2-Default> python .\mingw-bundledlls --copy .\bin\krita.exe
Traceback (most recent call last):
  File ".\mingw-bundledlls", line 146, in <module>
    main()
  File ".\mingw-bundledlls", line 120, in main
    all_deps = set(gather_deps(args.exe_file, path_prefixes, set()))
  File ".\mingw-bundledlls", line 76, in gather_deps
    output = subprocess.check_output(["objdump", "-p", path]).decode(
  File "C:\Users\Eli\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "C:\Users\Eli\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Eli\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Eli\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Setup: Windows 10 x64, msys2, python 3.5

**Comment by kelteseth** [comment]
Ok my bad! Apparently I did not add the "C:\msys64\mingw64\bin" to the PATH variable so he was unable to find objdump
